### ISSUE TITLE
PostgreSQL version?

### ISSUE THREAD

**Issue by ghenry** [jberger/VueChat#2]
Hi Joel,

Just enjoyed your presentation on YouTube for this. What version of Pg is being used here as I can't find reference to a message broker or pubsub online, apart from Mojo->Pg

Thanks.

**Comment by jberger** [comment]
The feature you are looking for is called NOTIFY. It seems that it exists at least since 9.0 which is far earlier than I'd go back to personally since I need newer features for just about everything I do. More detail here https://www.postgresql.org/docs/current/static/sql-notify.html
